image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm run build

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - octref.vetur@0.28.0:bW1RGNnmWYQO43JdJgK34w==